### ISSUE TITLE
Check to see if e-mail is already registered is missing

### ISSUE THREAD

**Issue by rubenve** [easydigitaldownloads/edd-auto-register#1]
There is no check to see if an e-mail address is already registered. If the email is already registered the purchase will be linked to the guest account.
I think it's better to have this check and throw an error message telling the user that the e-mail address already exists.

**Comment by grappler** [comment]
I just tested this today and when using an email that is already registered the purchase gets added to the user without the user needing to login.

I suppose this issue can be closed.
