### ISSUE TITLE
Auto detect users who are logged out

### ISSUE THREAD

**Issue by sumobi** [easydigitaldownloads/edd-auto-register#10]
If a logged out customer (guest) tries to purchase using their user account email it might be nice to prompt them that the email already exists, and show the password field. This way they can login and have the purchase attributed to their account. There might be a better way to do this.

**Comment by Softid30** [comment]
When I go to back-end and see one customer then choose see all products purchased by this customer is shows a list of all 3 products purchased but for 2 of them in the user column it says "guest". Any way to solve this at this moment.

**Comment by pippinsplugins** [comment]
This is resolved by setting the login / registration form options in the Misc tab.
