### ISSUE TITLE
Random plugin deactivation

### ISSUE THREAD

**Issue by ehrig** [easydigitaldownloads/edd-auto-register#12]
I am using EDD 2.3.2 and EDD auto register 1.2.1, and I am glad that such a plugin exists. But for some reason the plugin randomly deactivated itself. Is this a known issue? Any idea how I can get to the root of it?

**Comment by pippinsplugins** [comment]
Reported again here: https://easydigitaldownloads.com/support/topic/auto-register-multisite-edd-upgrades-auto-register-deactivating/

**Comment by pippinsplugins** [comment]
@ghost1227 Could you get this fixed?

**Comment by sumobi** [comment]
Fixed via https://github.com/easydigitaldownloads/edd-auto-register/commit/3eed12cc33b4988baec3aa7c01b4f49908704dc1
