### ISSUE TITLE
Not working with EDD 2.4.1

### ISSUE THREAD

**Issue by danwan** [easydigitaldownloads/edd-auto-register#14]
Plugin worked perfectly before EDD 2.4.
But since 2.4 and now with 2.4.1 it doesn't create user accounts anymore.

Dan

**Comment by pippinsplugins** [comment]
@ghost1227 How is your update coming along that should also resolve this issue?

**Comment by bizzthemes** [comment]
Any update on this?

**Comment by pippinsplugins** [comment]
I'm hoping to put some time on it this week.

**Comment by mindctrl** [comment]
It's working in my tests in EDD 2.4.2 and Auto Register 1.2.1. Is there another conflict here?

**Comment by pippinsplugins** [comment]
There are certain instances where it doesn't work. I know of a few of them and will be working through them later this week.

**Comment by sumobi** [comment]
Fixed via https://github.com/easydigitaldownloads/edd-auto-register/commit/3eed12cc33b4988baec3aa7c01b4f49908704dc1
