### ISSUE TITLE
Only auto register on specific downloads or downloads that belong to specific categories/tags

### ISSUE THREAD

**Issue by sumobi** [easydigitaldownloads/edd-auto-register#16]
> Is there some script I could put in my functions.php file to make auto register only work on specific EDD products or EDD categories? For example, I don't want auto register on ebooks but I do on courses.

Requested here:
https://wordpress.org/support/topic/select-product-or-category

**Comment by samikeijonen** [comment]
This is interesting. Just commenting so that I can follow up in here:)
