### ISSUE TITLE
Guest purchasers being forced to log in

### ISSUE THREAD

**Issue by EngageWP** [easydigitaldownloads/edd-auto-register#17]
Just fielded a client issue where every buyer was being forced to log in, despite not having an account to log into. I tracked it down to the recent Auto Register update. The problem lies in the remove_register_form() method, where there aren't any checks to see if the login form should be used. Instead of first checking to see if guest purchasing has been disabled and that the user is logged out, it automatically replaces the registration form with the login form. This is effectively disabling guest purchases. 

To get around this, I decided to keep 1.3 but add in the appropriate checks for displaying the login form. Also, I made the default return value "none". This seems to have resolved the issue in this case.

**Comment by pippinsplugins** [comment]
@EngageWP what did you have the registration / login form options set to in Downloads > Settings > Misc?

**Comment by EngageWP** [comment]
@pippinsplugins "Registration and Login Forms"

**Comment by mindctrl** [comment]
Another customer reported this and I've confirmed it locally. It's forcing login when the forms are set to show but guest purchases are still allowed.

![image](https://cloud.githubusercontent.com/assets/1254870/9172629/e86c9606-3f42-11e5-95cb-9bdb41ba274f.png)

**Comment by mindctrl** [comment]
@EngageWP willing to submit a PR for this?

**Comment by EngageWP** [comment]
@mindctrl Done

**Comment by pippinsplugins** [comment]
@EngageWP Awesome, thanks! See my one comment on the PR then we can merge it in.

**Comment by EngageWP** [comment]
@pippinsplugins Not a problem! Just pushed.
