### ISSUE TITLE
Disable auto register optionally for manual purchases

### ISSUE THREAD

**Issue by flowdee** [easydigitaldownloads/edd-auto-register#21]
Would be nice to disable the auto register when creating a manual payment

**Comment by pippinsplugins** [comment]
Thank you for the suggestion!

**Comment by grappler** [comment]
@flowdee You can use the new filter to disable auto register whenever you want. https://github.com/easydigitaldownloads/edd-auto-register/pull/23

**Comment by flowdee** [comment]
Thanks for the tip @grappler it's very useful.

Anyway it would be amazing to get a checkbox in order to enable/disable when creating a manual purchase.
