### ISSUE TITLE
Make auto register able to be called without a purchase ID

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/edd-auto-register#25]
Right now, the auto register in `mabe_insert_user` requires a payment ID to be supplied, which causes a problem in the new recurring with gateway payment profiles.

Basically Payment Profiles have to be created after the user, so we can properly attach the customer ID from the gateway to the user meta, but currently the profile is created, and then auto register triggers on the `edd_insert_payment` so we have an unattached EDD User/Customer and gateway customer. The next purchase made will create a new stripe customer since there isn't a customer profile ID in the user meta.

The plan is to make the auto register have 2 methods, one that creates a user and does nothing more, and one that handles the payment ID logic. This should be fully backwards compatible as it's just a logic check on if we should run the insert user or not upon inserting payment.

**Comment by pippinsplugins** [comment]
:+1:
