### ISSUE TITLE
Auto-login on modal purchases with Stripe doesn't work

### ISSUE THREAD

**Issue by tsudarshan** [easydigitaldownloads/edd-auto-register#27]
After much research, I figured that when I use a shortcode such as:

`<?php echo do_shortcode('[purchase_link id="193" text="Purchase" style="button" color="blue" direct="true"]'); ?>`

and the site is configured with Stripe gateway to open a modal for instant checkout, the user creation works great. But, it doesn't auto-login the user upon successful purchase. It does redirect to the intended page as specified in the Settings but there is no wplogin cookie being set.

This works great without modal - when the user goes through the regular checkout screen.

I figured out that Lines 377:384 in edd-auto-register.php play a role here and attempted to change this:

```
$maybe_login_user = function_exists( 'did_action' ) && did_action( 'edd_purchase' );
				$maybe_login_user = apply_filters( 'edd_auto_register_login_user', $maybe_login_user );

				if ( true === $maybe_login_user ) {

					edd_log_user_in( $user_id, $user_args['user_login'], $user_args['user_pass'] );

				}
```
to:

```
$maybe_login_user = function_exists( 'did_action' ) && did_action( 'edd_purchase' );
				$maybe_login_user = apply_filters( 'edd_auto_register_login_user', $maybe_login_user );

				// if ( true === $maybe_login_user ) {

					edd_log_user_in( $user_id, $user_args['user_login'], $user_args['user_pass'] );

				// }
```
by disabling the $maybe_login_user validation and then it works great with modal checkouts too.

This is a temporary fix but since there is no hook (atleast AFAIK) for this, it would be great if you could consider fixing this in your next release? Maybe atleast providing an option somewhere that can be toggled?

Please advice.

Thanks much for your support :)
-ST

**Comment by pippinsplugins** [comment]
Thanks! We'll get this resolved and release an update soon.

**Comment by tsudarshan** [comment]
Thanks, Pippin! Look forward to this fix in the next update :+1:
