### ISSUE TITLE
Overwrites payment user information with current user ID

### ISSUE THREAD

**Issue by NateWr** [easydigitaldownloads/edd-auto-register#28]
This is related to #21 and partially compensated for in the `edd_auto_register_disable` filter added in #23.

The plugin assumes the current user should be attached to the payment currently being made, which may not be the case for manual purchases or those created programmatically through some kind of third-party integration (my situation).

https://github.com/easydigitaldownloads/edd-auto-register/blob/master/edd-auto-register.php#L312

This created a bit of a headache for me in tracking down why the user ID in my `edd_insert_payment()` call was getting overwritten. My first thought was to pull a user ID from payment data when available:

```
				$user_id = get_current_user_id();

				// It's possible that the current logged-in user is not the
				// user attached to the purchase (eg - anual purchases)
				if ( !empty( $payment_data['user_info'] ) && !empty( $payment_data['user_info']['id'] ) ) {
					$user = get_user_by( 'id', $payment_data['user_info']['id'] );
					if ( is_a( $user, 'WP_User' ) ) {
						$user_id = $user->ID;
					}
				}
```

But now I'm wondering if this plugin should be a little more conservative in writing to `_edd_payment_user_id` and `_edd_payment_meta`. Is there any reason the `maybe_insert_user` function should do anything if a user ID is attached to the `$payment_data`? Could it not just check the data for a user ID and exit early if found?

```
		public function maybe_insert_user( $payment_id, $payment_data ) {

			// It's possible that the current logged-in user is not the
			// user attached to the purchase (eg - anual purchases)
			if ( !empty( $payment_data['user_info'] ) && !empty( $payment_data['user_info']['id'] ) ) {
				$user = get_user_by( 'id', $payment_data['user_info']['id'] );
				if ( is_a( $user, 'WP_User' ) ) {
					return;
				}
			}
```

You may have in mind some use-cases where that would cause problems, but I thought that might be a cleaner way to prevent third-party conflicts.

**Comment by pippinsplugins** [comment]
I think perhaps the better approach would be to add a check for Manual Purchases and then not use the current user ID if it's a manual purchase.

**Comment by michaelbeil** [comment]
I noticed this bug on AWP the other day. This works great!
