### ISSUE TITLE
Set the user ID on license keys generated by Software Licensing

### ISSUE THREAD

**Issue by ericnicolaas** [easydigitaldownloads/edd-auto-register#34]
When someone makes a purchase and you have Software Licensing installed, the behaviour I expected was that their licenses are correctly associated with the new user ID that is generated with EDD Auto Register. It appears that is not the case. 

On closer inspection, the SL function that generates a license is called on the `edd_complete_purchase` hook. Auto Register adds the user ID on the `edd_insert_payment` hook. I'm guessing `edd_insert_payment` happens after `edd_complete_purchase`. 

There are probably a few ways to solve this, but I'm going to push through a PR with a simple fix.

**Comment by pippinsplugins** [comment]
`edd_insert_payment` happens before `edd_complete_purchase`.

**Comment by pippinsplugins** [comment]
PR looks good. Merging and will deploy an update.
