### ISSUE TITLE
Warning: Invalid argument supplied for foreach()

### ISSUE THREAD

**Issue by sumobi** [easydigitaldownloads/edd-auto-register#36]
```
Warning: Invalid argument supplied for foreach() /wp-content/plugins/edd-auto-register/edd-auto-register.php on line 336
```

Seems to be related to Software Licensing

Ticket: https://wordpress.org/support/topic/error-in-new-version-3

**Comment by mindctrl** [comment]
Introduced here: https://github.com/easydigitaldownloads/edd-auto-register/pull/35

Code assumes the purchase has licenses. Should check that a license actually exists before the foreach.

**Comment by pippinsplugins** [comment]
Doh, fixing now.
