### ISSUE TITLE
Create user accounts on edd_insert_payment

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/edd-auto-register#5]
Instead of using the purchase process, it'd be best to tie into the `edd_insert_payment` hook. Doing a simply check on the payment to see if a user account is connected. If no user ID is set, create one.

Note: this should also properly attach the customer account if necessary.

**Comment by sumobi** [comment]
This will probably also fix: https://wordpress.org/support/topic/incompatibility-between-edd-braintree-and-edd-auto-register

**Comment by ghost1227** [comment]
@pippinsplugins if you hook `edd_insert_payment` you're running it after the payment completes... wouldn't that make it impossible to error out if the email already exists?

**Comment by pippinsplugins** [comment]
edd_insert_payment() runs before a payment is completed.

**Comment by sumobi** [comment]
Fixed via https://github.com/easydigitaldownloads/edd-auto-register/commit/3eed12cc33b4988baec3aa7c01b4f49908704dc1
