### ISSUE TITLE
Recurring purchases are being prevented for new customers

### ISSUE THREAD

**Issue by mintplugins** [easydigitaldownloads/edd-auto-register#52]
Because of the changes made in #50, Recurring purchases by non-logged-in customers are being prevented with this error message:

```
You must be logged in to purchase a subscription
```

The problem there is that user accounts are automatically created using the payment information. But EDD Recurring prevents the payment unless a user account exists. We may need to add an exception to Auto Register for Recurring Payments.

**Comment by mintplugins** [comment]
This will require some thorough testing:

Testing steps:
1. Purchase a product as a guest with Auto Register deactivated
2. Enable Auto Register, and purchase a recurring, licensed product
3. Make sure the auto-created account is pending verification and you don't get access to the first purchase. 
4. Make sure the subscription was properly created.
5. Make sure the license has the user attached to it. 

Free Downloads testing steps:
1. Make sure you can download a free product through FD and automatically get a user account created.

**Comment by mintplugins** [comment]
@SDavisMedia Tagging you here for if you get a free moment to test - thanks! No pressure.

**Comment by SDavisMedia** [comment]
Replicated the checkout error on `master`. 

Confirmed the expected behavior for for the testing scenario above on `issue/52`. :+1:

**Comment by pippinsplugins** [comment]
@mintplugins Chris had a few changes for the PR. Could you push those up?

**Comment by Kubitomakita** [comment]
Is there a chance for the fix? All sales are blocked right now and I have some frustrated customers, not mentioning myself.

I tried to update the plugin with #53 branch but it didn't help. All I get is "You must be logged in to purchase a subscription". Can I downgrade Recurring Payments plugin or Software Licensing to get this working ASAP?

**Comment by Kubitomakita** [comment]
The fix is not working in Multisite. I have two websites on the network - Store and Documentation site.

**Comment by pippinsplugins** [comment]
Until we have this finished, please downgrade to the previous version.

**Comment by Kubitomakita** [comment]
Unfortunately, downgrading doesn't help at all. Tried 3 last versions.

**Comment by pippinsplugins** [comment]
Then you're facing a different problem than this. Can you please open a
support ticket so we can assist you?
https://easydigitaldownloads.com/support

**Comment by pippinsplugins** [comment]
Another way to replicate this error:

1. Enable Auto Register
2. Enable Recurring Payments
3. Enable Stripe and Stripe Checkout option
4. Attempt to purchase a subscription with a new email while logged out

**Comment by pippinsplugins** [comment]
Ignore the part about Stripe Checkout. This happens with regular Stripe too.

**Comment by stevejburge** [comment]
Can confirm this problem with Stripe. It's the second time the problem has appeared for us, and it happens across multiple sites.

We've disabled Auto Register for now.

**Comment by mintplugins** [comment]
Just re-tested these steps:

- Enable Auto Register
- Enable Recurring Payments
- Enable Stripe (normal mode and also tested with Stripe Checkout mode)
- Attempt to purchase a subscription with a new email while logged out
- Purchase successful and auto account registration also successfull

**Comment by hiddenpearls** [comment]
@cklosowski @pippinsplugins I am having the same issue. Not sure what is the main reason but appears to be conflict with Stripe. 

1.3.10 is not pushed on wordpress.org?

**Comment by cklosowski** [comment]
@hiddenpearls it appears it was tagged, and uploaded, but the stable version was never changed in the readme. I'll investigate to see what's going on.

**Comment by cklosowski** [comment]
Keep in mind this is tagged for 1.3.11, so I"m guessing we had an issue in 1.3.10 that made it so we didn't tag it, but again I'll look into it.

**Comment by cklosowski** [comment]
Yes, this is the current status:
```
To re-cap, here is a timeline of events:

This issue was created and the PR was submitted, merged, and released in 1.3.10
1.3.10 caused problems with recurring
The WP Plugin repo for Auto Register was rolled back from 1.3.10 to 1.3.9, a couple of users were affected
Issue #52 was opened, using master as the source of the branch, which included this issue's PR code
Issue #52 was completed and merged.
I have tested to make sure Auto Register still works with Free Downloads, which is what this issue is really for.
Therefore, this issue is now being closed.
```

**Comment by cklosowski** [comment]
@hiddenpearls "This" being issue #50

**Comment by hiddenpearls** [comment]
@cklosowski Thanks!

I have submitted a support request to EDD support though.

**Comment by cklosowski** [comment]
I retested the steps here: https://github.com/easydigitaldownloads/edd-auto-register/issues/52#issuecomment-366382902

Testing steps:
- [x] Purchase a product as a guest with Auto Register deactivated
- [x] Enable Auto Register, and purchase a recurring, licensed product
- [x] Make sure the auto-created account is pending verification and you don't get access to the first purchase.
- [x] Make sure the subscription was properly created.
- [x] Make sure the license has the user attached to it.

Free Downloads testing steps:
- [x] Make sure you can download a free product through FD and automatically get a user account created.

**Comment by cklosowski** [comment]
All my above testing with with latest EDD, with Stripe on latest.

**Comment by cklosowski** [comment]
And latest Free Downloads
