### ISSUE TITLE
Use of edd_debug_log is making 2 entries on every page load.

### ISSUE THREAD

**Issue by misulicus** [easydigitaldownloads/edd-auto-register#55]
having debug enabled on EDD you get an entry in the log for 2 instances on EACH page refresh so that can get you a pretty huge log.
The 2 lines below seem too DRASTIC and could be removed:

https://github.com/easydigitaldownloads/edd-auto-register/blob/master/edd-auto-register.php#L65
https://github.com/easydigitaldownloads/edd-auto-register/blob/master/edd-auto-register.php#L131

**Comment by cklosowski** [comment]
Agreed, these should be put into a location where they are only logging when Auto Register starts to take action, not on every page load.

While it's useful to know when it starts, having it on every page load is just noise to make helpful logs get lost in.
