### ISSUE TITLE
3.0 Compatibility: edd_debug_log needs to do an EDD version check

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/edd-auto-register#60]
With the move of EDD Core 3.0 moving to a hook that is later the definition of `edd_debug_log` in Auto Register has a `! function_exists` means that core has not registered the function yet, and as such EDD Core fatal errors trying to redefine it.

**Comment by misulicus** [comment]
@cklosowski postin here to not open another issue.
Someone reported he can't activate EDD after updating to 2.9.10

```
Fatal error: Cannot redeclare edd_debug_log() (previously declared in D:\MAMP\htdocs\edd\wp-content\plugins\edd-auto-register\edd-auto-register.php:518) in D:\MAMP\htdocs\edd\wp-content\plugins\easy-digital-downloads\includes\class-edd-logging.php on line 537
```

I get the same error locally if i try to activate EDD when auto register is enabled.

**Comment by cklosowski** [comment]
@misulicus Ok I'll get this bumped up. in the mean time, can you deactivate Auto Register and then activate EDD, then re-actiavte auto register? The way this is written shouldn't be a problem. 2.9.10 and 2.9.9 didn't have an fundamental change in the way things are loaded here.

**Comment by misulicus** [comment]
Deactivated Auto register -> Activating EDD -> Activating Auto Register works correctly.
