### ISSUE TITLE
Update plugin on wordpress.org

### ISSUE THREAD

**Issue by polevaultweb** [easydigitaldownloads/edd-auto-register#66]
The plugin at https://wordpress.org/plugins/edd-auto-register/ is a version behind, please can you release v1.3.10

**Comment by cklosowski** [comment]
@polevaultweb We're actually waiting on a final approval from internal to release it. Last time we released some of this code we had some issues and had to rollback.

We've refactored it slightly and have it running on the EDD site. I suspect we'll release it in the next week or two.

**Comment by polevaultweb** [comment]
Thanks @cklosowski 👍
