### ISSUE TITLE
Can you provide a filter example of how to modify the default role of the user when they are created?

### ISSUE THREAD

**Issue by haziqmus** [easydigitaldownloads/edd-auto-register#72]
Can you provide a filter example of how to modify the default role of the user when they are created?

**Comment by mintplugins** [comment]
@haziqmus You can find all of the available filters in this plugin by searching for "apply_filters" on the repo:

https://github.com/easydigitaldownloads/edd-auto-register/search?q=apply_filters&unscoped_q=apply_filters

None of those filters are useful for your request here. However, auto register uses the WordPress default role setting here:
https://github.com/easydigitaldownloads/edd-auto-register/blob/b47cd0d0654c45a021a1f3c2452a4ff19b7f1da5/edd-auto-register.php#L407

The default role for new users can be set in Administration Screens > Settings > General.

So you'll want to look at setting that value. For anything further please reach out to a consultant here:
https://easydigitaldownloads.com/consultants/
