### ISSUE TITLE
Free Download's "Bypass Auto Registration" setting not working

### ISSUE THREAD

**Issue by dgoldak** [easydigitaldownloads/edd-auto-register#75]
### Expected behavior
When `Bypass Auto Registration` is enabled, Free Downloads customers should not get registered.

### Actual behavior
Free Downloads customers get registered despite `Bypass Auto Registration` being enabled.

It appears to have stopped working somewhere between 1.3.10 and 1.3.13. 

### Steps to reproduce the behavior
1) Enable `Bypass Auto Registration` in the Free Downlaods settings.
2) "Purchase" a product via Free Downloads modal.
3) Confirm email address was not registered.

### Information:
PHP Version: 7.2

EDD Auto Register Version (or branch): `master`

EDD Version (or branch): `master`

WordPress Version: 5.3.2

Any other relevant information:
https://secure.helpscout.net/conversation/1051498880/141821?folderId=1847242

**Comment by dgoldak** [comment]
It appears this is the issue that broke the setting: https://github.com/easydigitaldownloads/edd-auto-register/issues/43

**Comment by ashleyfae** [comment]
I think this caused it: https://github.com/easydigitaldownloads/edd-auto-register/issues/50 The hook was changed from `edd_insert_payment` to `edd_payment_saved`. The Free Downloads plugin is unhooking `edd_insert_payment`, which is no longer used.

Will confirm, but this might need to be fixed in Free Downloads.

**Comment by ashleyfae** [comment]
Closing in favour of https://github.com/easydigitaldownloads/edd-free-downloads/issues/330 in the Free Downloads repo.
