### ISSUE TITLE
How to call a function to create a user programmatically?

### ISSUE THREAD

**Issue by sadmansh** [easydigitaldownloads/edd-auto-register#76]
Is there a function I can call that creates a user and emails them their password?

**Comment by cklosowski** [comment]
EDD Auto Register just uses the normal WordPress methods to create users:
https://developer.wordpress.org/reference/functions/wp_create_user/

For future requests like this, please use the support form as GitHub is only used for development tracking at this time:
https://easydigitaldownloads.com/support.
