### ISSUE TITLE
Support Stripe Checkout

### ISSUE THREAD

**Issue by sumobi** [easydigitaldownloads/edd-auto-register#8]
We should support Stripe Checkout as requested here:
https://easydigitaldownloads.com/support/topic/creating-a-wordpress-user-account/#post-356787

**Comment by sumobi** [comment]
Fixed via https://github.com/easydigitaldownloads/edd-auto-register/commit/3eed12cc33b4988baec3aa7c01b4f49908704dc1

**Comment by mindctrl** [comment]
Opening this back up after a customer [reported](https://secure.helpscout.net/conversation/111044104/14459/) that when using Buy Now with Stripe and Auto Register, the customers can't view the receipt. They get the "Sorry, trouble retrieving payment receipt" message. 

This might be a core issue, and is possibly related to Free Downloads issue  https://github.com/easydigitaldownloads/edd-free-downloads/issues/18#issuecomment-128375557.

**Comment by pippinsplugins** [comment]
Can they view it once logged in?

**Comment by mindctrl** [comment]
@pippinsplugins yes if they manually log in it shows in purchase history.

**Comment by pippinsplugins** [comment]
I've just tested this again and with the changes in #27, it all works properly.
