### ISSUE TITLE
New user email not sent when Auto Register active

### ISSUE THREAD

**Issue by shaynesanderson** [easydigitaldownloads/edd-auto-register#80]
### Expected behavior
When using the [edd_register] shortcode, and filling out the registration form a new user email should be sent to the user after a successful registration.

### Actual behavior
When Auto Register is activated, completing a registration on the form produced by [edd_register], no new user email is sent.

### Steps to reproduce the behavior
1) Place [edd_register] on a page
2) Activate Auto Register
3) Complete registration form for a new (unique) user and no email will be sent.
4) Note: The "Disable User Email" option is not enabled in Downloads-->Settings-->Extensions.

### Information:
PHP Version: 7.4.1

EDD Auto Register Version (or branch): 1.3.13

EDD Version (or branch): 2.9.26

WordPress Version: 5.5.1

**Comment by ashleyfae** [comment]
Probably due to this running all the time:

```php
// stop EDD from sending new user notification, we want to customize this a bit
remove_action( 'edd_insert_user', 'edd_new_user_notification', 10, 2 );
```

should probably only remove that just prior to EDD Auto Register creating a user.
